[[main]]
name = "À propos"
url = "/#about"
weight = 2

[[main]]
name = "Compétences"
url = "/#skills"
weight = 3

[[main]]
name = "Expérience"
url = "/#experience"
weight = 4

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 4.5

[[main]]
name = "Contact"
url = "/#contact"
weight = 5